- file: dest=/var/apps/ state=directory

- apt: pkg=libapr1 state=present
- apt: pkg=graphviz state=present
- shell: ln -f -s /usr/bin/dot /usr/local/bin/dot

- get_url: url=https://s3-eu-west-1.amazonaws.com/reka/reka.tar.gz dest=/var/apps/reka.tar.gz
  tags:
    - deploy

#- unarchive: src=/var/apps/reka.tar.gz dest=/var/apps/
- shell: cd /var/apps/ && tar zxvf reka.tar.gz
  tags:
    - deploy

- name: send api.reka
  template: src=api.reka.j2 dest=/var/apps/reka/etc/apps/api.reka
  notify:
    - restart reka
  tags:
    - deploy

- name: allow port 80,443
  shell: ufw allow 80,443/tcp
  tags:
    - network

- name: allow port 8000:8999
  shell: ufw allow 8000:8999/tcp
  tags:
    - network

- name: send upstart config
  template: src=reka.upstart.conf.j2 dest=/etc/init/reka.conf
  notify:
    - restart reka
  tags:
    - deploy